### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.View.getContext()' on a null object reference                                                                at pl.allegro.fogger.utils.ScreenShooter.createViewScreenshot

### ISSUE THREAD

**Issue by ghost** [allegro/fogger#10]
<pl.allegro.fogger.ui.drawer.DrawerLayoutWithBlurredBackground
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/drawer_layout"
    android:background="@color/black"
    android:layout_width="match_parent"
    android:layout_height="match_parent"

```
<include layout="@layout/activity_base"
         android:id="@+id/fragmentPlaceholder"
         android:tag="@string/view_with_drawer_tag"
    />

<android.support.design.widget.NavigationView
    android:id="@+id/container"
    android:layout_width="wrap_content"
    android:layout_height="match_parent"
    android:background="#90444444"
    android:layout_gravity="start"
    android:fitsSystemWindows="false">
    <FrameLayout
        android:id="@+id/drawer_frag_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        android:choiceMode="singleChoice"
        android:divider="@android:color/transparent"
        android:dividerHeight="0dp" />

</android.support.design.widget.NavigationView>
```

</pl.allegro.fogger.ui.drawer.DrawerLayoutWithBlurredBackground>

This is my layout

**Comment by arjunhegde372** [comment]
<pl.allegro.fogger.ui.drawer.DrawerLayoutWithBlurredBackground
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/drawer_layout"
    android:background="@color/black"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <include layout="@layout/activity_base"
             android:id="@+id/fragmentPlaceholder"
             android:tag="@string/view_with_drawer_tag"
        />

    <android.support.design.widget.NavigationView
        android:id="@+id/container"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:background="#90444444"
        android:layout_gravity="start"
        android:fitsSystemWindows="false">
        <FrameLayout
            android:id="@+id/drawer_frag_container"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_gravity="start"
            android:choiceMode="singleChoice"
            android:divider="@android:color/transparent"
            android:dividerHeight="0dp" />

    </android.support.design.widget.NavigationView>
</pl.allegro.fogger.ui.drawer.DrawerLayoutWithBlurredBackground>

This is my layout

**Comment by pawelByszewski** [comment]
Could you post whole layout or some kind of complete equivalent of layout?  What context are you useing the layout in? activity, fragment or dynamically inflated view?

**Comment by arjunhegde372** [comment]
```
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    android:orientation="vertical">

    <FrameLayout
        android:id="@+id/content_frame"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@+id/footer_frame"
        />

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="@color/black_translucent"
        android:gravity="end">

        <ImageView
            android:id="@+id/pan_cake_menu"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentStart="true"
            android:layout_centerVertical="true"
            android:layout_margin="5dp"
            android:src="@drawable/ic_outline_pancake"/>

        <ImageView
            android:id="@+id/search"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentEnd="true"
            android:layout_centerVertical="true"
            android:layout_margin="5dp"
            android:src="@drawable/ic_outline_search"/>

    </RelativeLayout>

    <FrameLayout
        android:id="@+id/footer_frame"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:background="@color/footer_background"/>

</RelativeLayout>
```

This is my activity_base layout

**Comment by pawelByszewski** [comment]
Unfortunately in posted layout I can not find ```pl.allegro.fogger.ui.drawer.DrawerLayoutWithBlurredBackground``` so it will be hard reproduce the error

**Comment by arjunhegde372** [comment]
<pl.allegro.fogger.ui.drawer.DrawerLayoutWithBlurredBackground
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/drawer_layout"
    android:background="@color/black"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <RelativeLayout
android:tag="@string/view_with_drawer_tag"
android:id="@+id/fragmentPlaceholder"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    android:orientation="vertical">

    <FrameLayout
        android:id="@+id/content_frame"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@+id/footer_frame"
        />

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="@color/black_translucent"
        android:gravity="end">

        <ImageView
            android:id="@+id/pan_cake_menu"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentStart="true"
            android:layout_centerVertical="true"
            android:layout_margin="5dp"
            android:src="@drawable/ic_outline_pancake"/>

        <ImageView
            android:id="@+id/search"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentEnd="true"
            android:layout_centerVertical="true"
            android:layout_margin="5dp"
            android:src="@drawable/ic_outline_search"/>

    </RelativeLayout>

    <FrameLayout
        android:id="@+id/footer_frame"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:background="@color/footer_background"/>

</RelativeLayout>

    <android.support.design.widget.NavigationView
        android:id="@+id/container"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:background="#90444444"
        android:layout_gravity="start"
        android:fitsSystemWindows="false">
        <FrameLayout
            android:id="@+id/drawer_frag_container"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_gravity="start"
            android:choiceMode="singleChoice"
            android:divider="@android:color/transparent"
            android:dividerHeight="0dp" />

    </android.support.design.widget.NavigationView>
</pl.allegro.fogger.ui.drawer.DrawerLayoutWithBlurredBackground>

Can you check now please?

**Comment by pawelByszewski** [comment]
I could not check it now, but I will do it as soon as possible

**Comment by arjunhegde372** [comment]
Thanks!!

**Comment by adamdubiel** [comment]
This repo is no logner maintained - closing.
