### ISSUE TITLE
App crashed while scrolling and opeing dialog

### ISSUE THREAD

**Issue by krupinder955** [allegro/fogger#13]
08-23 18:46:12.067 12125-12125/com.allegrogroup.android.view.counteredittext.sample E/AndroidRuntime: FATAL EXCEPTION: main                                                                                                       Process: com.allegrogroup.android.view.counteredittext.sample, PID: 12125                                                                                                       java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.                                                                                                           at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)                                                                                                           at android.os.Handler.handleCallback(Handler.java:742)                                                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)                                                                                                           at android.os.Looper.loop(Looper.java:154)                                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5529)                                                                                                           at java.lang.reflect.Method.invoke(Native Method)                                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)                                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)                                                                                                        Caused by: rx.exceptions.OnErrorNotImplementedException: Only the original thread that created a view hierarchy can touch its views.                                                                                                           at rx.Observable$30.onError(Observable.java:7358)                                                                                                           at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:154)                                                                                                           at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)                                                                                                           at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:197)                                                                                                           at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170)                                                                                                           at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)                                                                                                           at android.os.Handler.handleCallback(Handler.java:742)                                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)                                                                                                            at android.os.Looper.loop(Looper.java:154)                                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5529)                                                                                                            at java.lang.reflect.Method.invoke(Native Method)                                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)                                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)                                                                                                         Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.                                                                                                           at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6593)                                                                                                           at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:966)                                                                                                           at android.view.ViewGroup.invalidateChild(ViewGroup.java:5082)                                                                                                           at android.view.View.invalidateInternal(View.java:12730)                                                                                                           at android.view.View.invalidate(View.java:12666)                                                                                                           at android.view.View.invalidateDrawable(View.java:16811)                                                                                                           at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:385)                                                                                                           at android.widget.ScrollBarDrawable.invalidateDrawable(ScrollBarDrawable.java:372)                                                                                                           at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:385)                                                                                                           at android.graphics.drawable.NinePatchDrawable.setAlpha(NinePatchDrawable.java:331)                                                                                                           at android.widget.ScrollBarDrawable.setAlpha(ScrollBarDrawable.java:326)                                                                                                           at android.view.View.onDrawScrollBars(View.java:13877)                                                                                                           at android.view.View.onDrawForeground(View.java:17680)                                                                                                           at android.view.View.draw(View.java:16212)                                                                                                           at android.widget.ScrollView.draw(ScrollView.java:1712)                                                                                                           at android.view.View.draw(View.java:16113)                                                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3610)                                                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)                                                                                                           at android.view.View.draw(View.java:16111)                                                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3610)                                                                                                           at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1089)                                                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)                                                                                                           at android.view.View.draw(View.java:16111)                                                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3610)                                                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)                                                                                                           at android.view.View.draw(View.java:16111)                                                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3610)                                                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)                                                                                                           at android.view.View.draw(View.java:16204)                                                                                                           at com.android.internal.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:500)                                                                                                           at android.view.View.draw(View.java:16113)                                                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3610)                                                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)                                                                                                           at android.view.View.draw(View.java:16204)                                                                                                           at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2692)                                                                                                           at pl.allegro.fogger.utils.ScreenShooter.createScreenShot(ScreenShooter.java:71)                                                                                                           at pl.allegro.fogger.utils.ScreenShooter.createViewScreenshot(ScreenShooter.java:50)                                                                                                           at pl.allegro.fogger.utils.ScreenShooter.createAppScreenshotInScale(ScreenShooter.java:42)                                                                                                           at pl.allegro.fogger.utils.ScreenShooter.createScreenShot(ScreenShooter.java:37)                                                                                                           at pl.allegro.fogger.ui.BlurredBackgroundAdapter.lambda$prepareBlurredBackgroundForActivity$0(BlurredBackgroundAdapter.java:74)

**Comment by adamdubiel** [comment]
This repo is no logner maintained - closing.
