### ISSUE TITLE
Lower version of minSdkVersion

### ISSUE THREAD

**Issue by polok** [allegro/fogger#5]
Hi,

You did awesome work! I have one question to the minSdkVersion. Right now it is set to 15. What I can see this could be set to one level below - 14. Maybe I am missing something in the library but still quite many apps are supported from Android 4.0 and will be nice to use it there directly.

Regards

**Comment by pawelByszewski** [comment]
Thanks Polok, good point. 
I have done a little bit refactoring so I try downgrade minSdk and release new version.

**Comment by polok** [comment]
Cool, looking forward to check it!

**Comment by pawelByszewski** [comment]
@polok do you have a device with api level 14 on board?

**Comment by polok** [comment]
Unfortunately not real one, only emulator ;/
