### ISSUE TITLE
Blurred Images

### ISSUE THREAD

**Issue by EzequielAdrianM** [allegro/fogger#8]
This is not an issue, but a question.

Could it be possible to blur only an ImageView element?

**Comment by pawelByszewski** [comment]
Actually there isn't. IMO it is outside the scope of responsibility of the lib, but I could add if you still need this.

**Comment by EzequielAdrianM** [comment]
I managed to solve my problem. But if you want to add it to your library it would be Great!

This is the code that worked for me:

    public static Bitmap blur(Context context, Bitmap image) {
        final float BITMAP_SCALE = 0.4f;
        final float BLUR_RADIUS = 7.5f;
        int width = Math.round(image.getWidth() * BITMAP_SCALE);
        int height = Math.round(image.getHeight() * BITMAP_SCALE);
        Bitmap inputBitmap = Bitmap.createScaledBitmap(image, width, height, false);
        Bitmap outputBitmap = Bitmap.createBitmap(inputBitmap);
        RenderScript rs = RenderScript.create(context);
        ScriptIntrinsicBlur theIntrinsic = ScriptIntrinsicBlur.create(rs, Element.U8_4(rs));
        Allocation tmpIn = Allocation.createFromBitmap(rs, inputBitmap);
        Allocation tmpOut = Allocation.createFromBitmap(rs, outputBitmap);
        theIntrinsic.setRadius(BLUR_RADIUS);
        theIntrinsic.setInput(tmpIn);
        theIntrinsic.forEach(tmpOut);
        tmpOut.copyTo(outputBitmap);
        return outputBitmap;
    }

**Comment by RosesJack** [comment]
Hello ,I have a question about your code ,could I ask like this? why you did not to call destroy when fuction over?  did it is necessary to call the destroy. the `destroy` is theIntrinsic.destroy(),rs.destroy(),

**Comment by EzequielAdrianM** [comment]
I didn't see any significant changes in memory after adding destroy() method. Probably because my bitmap is small and, it is even resized again in the function. Thanks for the suggestion.
